In [4]:
import numpy as np
marks = np.array([92,61,45,78,33,55])
print(marks)

print(np.where(marks>=75 ,"A", np.where(marks>=50, "B", "C")))

[92 61 45 78 33 55]
['A' 'B' 'C' 'A' 'C' 'B']


In [5]:
a= np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

print(a*b)
print(np.dot(a,b))
print(a@b)

[5 8 9 8 5]
35
35


In [ ]:
s1= [72, 85, 60, 91]
s2 = [45,30,98,55]
s3 = [88, 66, 74, 100]
old = np.array([['62', '71', '55', '80'],
                ['49', '58', '66', '73']])

# 1
table = np.array([s1,s2,s3])
print(table)

#2


[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]


In [ ]:
#q2
