In [1]:
import numpy as np

In [7]:
#arithmatic operations
a = np.arange(10)
print(a)
a= a+5
print("added 5:", a)
print("multiplied by 5:", a*5)
print("exponentiated:", a**2)

[0 1 2 3 4 5 6 7 8 9]
added 5: [ 5  6  7  8  9 10 11 12 13 14]
multiplied by 5: [25 30 35 40 45 50 55 60 65 70]
exponentiated: [ 25  36  49  64  81 100 121 144 169 196]


In [13]:
# now with 2 arrays

x = np.arange(10)
print(x)
y =np.arange(11,21)
print(y)
print("added:", x+y)
print("multiplied:", x*y)
print("dot product:", x@y)



[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
added: [11 13 15 17 19 21 23 25 27 29]
multiplied: [  0  12  26  42  60  80 102 126 152 180]
dot product: 780


In [14]:
#comparision operations - boolean arrays

x = np.arange(5)
y = np.arange(1,6)
print("x:", x)
print("y:", y)
print(x==y)
print(x>y)
print(x<y)

x: [0 1 2 3 4]
y: [1 2 3 4 5]
[False False False False False]
[False False False False False]
[ True  True  True  True  True]


In [35]:
# np.random.seed()
# 
np.random.seed(42)  # Set the seed for reproducibility
np.random.rand(1)


np.random.randn(10)


array([-1.11188012,  0.31890218,  0.27904129,  1.01051528, -0.58087813,
       -0.52516981, -0.57138017, -0.92408284, -2.61254901,  0.95036968])

In [68]:
#np.random.randint(low,high,size)

np.random.randint(0,10,size=(3,4))

array([[7, 6, 8, 7],
       [4, 1, 4, 7],
       [9, 8, 8, 0]])

#class question

set seed = 42 and simulate 10 dice rolls (value 1-6) using radint

In [77]:
np.random.seed(42)
np.random.randint(1,7,size=10)

array([4, 5, 3, 5, 5, 2, 3, 3, 3, 5])

In [ ]:
#q3
np.random.rand()
