What is Numpy?


In [ ]:
! pip3 install numpy


In [3]:
#numpy
import numpy as np
print("mai pagal hu")

mai pagal hu


In [5]:
# arr=np.array([1, 2, 3, 4, 5])
# print(arr)
print("mai pagal hu")


mai pagal hu


In [ ]:
#q1

print(np.arange(1,10,1))

#q2
print(np.zeros((3,3)))
print(np.ones((3,3)))

#q3

print(np.arange(2,21,2))

#q4

print(np.linspace(0,1,5))

#q5 create 4d 



[1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 2  4  6  8 10 12 14 16 18 20]
[0.   0.25 0.5  0.75 1.  ]


In [18]:
arr = np.arange((4*5)).reshape(5,4)
print(arr)

print(arr[::4,::3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  3]
 [16 19]]
