# 🧩 Day 1 Practice — 15 Questions (up to Slicing)

**Topics covered:** array creation · `dtype` / `astype` · attributes · indexing · slicing · boolean indexing
**Level:** Medium · **Rule:** solve using only these topics — no loops!

**Q1.** Create an array of the first 12 **odd numbers** using a single **np.arange** call.

**Q2.** Using **np.linspace**, create 9 equally spaced values from 5 to 45. Before running, **predict the gap** between consecutive values - then verify.

**Q3.** Create **np.arange(1, 10)** and **np.linspace(1, 9, 9)**. Print both and compare their **dtype**. Why are they different?

**Q4.** Create a **6x6 identity matrix** with integer dtype - the output must show no decimal points.

**Q5.** Create a **3x4 matrix** where every element is **5**, and report its shape, size, and ndim.

**Q6.** Given **a = np.array([2, 4, 6])** and **b = np.array([2.0, 4.0, 6.0])** - check both dtypes, then convert b to int with **astype** and verify the dtypes now match.

**Q7.** **Predict the exact output** of **np.array([10.9, 25.5, 39.99]).astype(int)** before running it. What rule does the result prove?

**Q8.** Given **arr = np.arange(10, 101, 10)** - extract: (a) the 4th element, (b) the last element using negative indexing, (c) the 2nd-last element.

**Q9.** From the same arr, slice out exactly **[30 40 50 60]**, and separately produce the **full array in reverse**.

**Q10.** Given **arr = np.arange(1, 21)** - extract **every 3rd element starting from index 1** (result: 2, 5, 8, ...).

**Q11.** Using **one slice only**, extract everything from arr (1-20) EXCEPT the first two and the last two elements.

**Q12.** Using the matrix below, extract: (a) the **3rd row**, (b) the **last column**, (c) the **centre 3x3 block**.
```python
m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])
```

**Q13.** From the same matrix, extract the **four corner elements** as a 2x2 array - using **step slicing only**.

**Q14.** From the same matrix, extract **every alternate row AND every alternate column** at the same time (the result is 3x3).

**Q15.** Given the marks array below - (a) extract all marks **greater than 60**; (b) extract marks **between 50 and 80** using two conditions with & (remember the parentheses!).
```python
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])
```

In [3]:
! pip3 install numpy as np
import numpy as np

ERROR: Could not find a version that satisfies the requirement as (from versions: none)

[notice] A new release of pip is available: 25.2 -> 26.2
[notice] To update, run: pip install --upgrade pip
ERROR: No matching distribution found for as


In [4]:
# Q1
a = np.arange(1,25,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [5]:
# Q2
b = np.linspace(5,45,9)
print(b)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [8]:
# Q3
c = np.arange(1,10)
d = np.linspace(1,9,9)
print(c)
print(d)
print(c.dtype)
print(d.dtype)


[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
int64
float64


In [10]:
# Q4
e = np.eye(6 , dtype = int)
print(e)
print(e.dtype)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
int64


In [12]:
# Q5
f =np.full((3,4),5)
print(f)
print("f.dtype:", f.dtype)
print("f.ndim:", f.ndim)
print("f.shape:", f.shape)
print("f.size:", f.size)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
f.dtype: int64
f.ndim: 2
f.shape: (3, 4)
f.size: 12


In [ ]:
# Q6


In [ ]:
# Q7


In [ ]:
# Q8


In [ ]:
# Q9


In [ ]:
# Q10


In [ ]:
# Q11


In [ ]:
# Q12


In [ ]:
# Q13


In [ ]:
# Q14


In [ ]:
# Q15


---
✅ **Done?** Cross-check every slicing answer by predicting the output *before* running the cell — that habit is what builds real logic.