# NumPy Practice Session

Quick one-line recaps only — the focus here is practice. For each topic, solve the questions in the empty code cells provided.


## 1. Array Creation Basics

_`np.array(list)` → from list | `np.zeros(shape)` → all 0s | `np.ones(shape)` → all 1s | `np.full(shape, val)` → custom value | `np.arange(start,stop,step)` → like range()_


**Q1.1** Create a 1D array of 6 numbers of your choice.

In [2]:
import numpy as np

In [3]:
# Write your code here
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

**Q1.2** Create a 3x3 array of zeros and a 2x2 array filled with the value 7.

In [8]:
# Write your code here

print(np.zeros((3,3)))
print(np.full((2,2),7))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7]
 [7 7]]


**Q1.3** Create an array of odd numbers from 1 to 21 using `arange`.

In [11]:
# Write your code here
print(np.arange(1,22,2))

[ 1  3  5  7  9 11 13 15 17 19 21]


## 2. Advanced Creation

_`.reshape(r,c)` → change shape | `np.linspace(start,stop,num)` → num evenly spaced values | `np.eye(n)` → n×n identity matrix_


**Q2.1** Create numbers 0 to 11 using `arange` and reshape into a 3x4 matrix.

In [12]:
# Write your code here
print(np.arange(0,12).reshape((3,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Q2.2** Generate 7 evenly spaced values between 10 and 50 using `linspace`.

In [13]:
# Write your code here
print(np.linspace(10,50,7))

[10.         16.66666667 23.33333333 30.         36.66666667 43.33333333
 50.        ]


**Q2.3** Create a 5x5 identity matrix.

In [15]:
# Write your code here
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 3. Array Attributes

_`.shape` → dimensions tuple | `.ndim` → no. of dimensions | `.size` → total elements | `.dtype` → data type_


**Q3.1** Create a (4,3) array and print its shape, ndim, size, and dtype.

In [19]:
# Write your code here
x = np.arange(12).reshape(4,3)
print(x.shape)
print(x.ndim)
print(x.dtype)

(4, 3)
2
int64


**Q3.2** Create a (3,) vector and check if it's compatible for a dot product with a (5,3) matrix.

In [ ]:
# Write your code here
a = np.arange(3).reshape(3,)
b = np.arange(15).reshape(5,3)
print(a@b)

# not compatible


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)

## 4. Indexing & Slicing

_`arr[i]` / `arr[r,c]` → access | `arr[a:b, c:d]` → sub-matrix | `arr[::step]` → step slicing | `arr[::-1]` → reverse_


**Q4.1** Create a 4x4 array with values 1-16. Extract row 2, column 3.

In [40]:
# Write your code here
mat = np.arange(1,17).reshape(4,4)
print(mat)
print(mat[2:3])
print(mat[:,-1])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11 12]]
[ 4  8 12 16]


**Q4.2** From the same array, extract the sub-matrix of the first two rows and last two columns.

In [43]:
# Write your code here
print(mat[0:2])
print(mat[:,2:4])

[[1 2 3 4]
 [5 6 7 8]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


**Q4.3** Reverse the array row-wise, then column-wise.

In [48]:
# Write your code here
print(mat[::-1])
print(mat[:,::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


**Q4.4** Print every 3rd element of a 1-20 array.

In [52]:
# Write your code here
np.arange(1,21,3)

array([ 1,  4,  7, 10, 13, 16, 19])

## 5. Data Types & Coercion

_Mixed types auto-upcast to one common dtype | `.astype(type)` → explicit conversion_


**Q5.1** Create an array mixing ints and floats — check the resulting dtype.

In [53]:
# Write your code here
x = np.array([1,2.5,7,8.4])
print(x.dtype)


float64


**Q5.2** Convert a float array [1.9, 2.5, 3.1] to integers using astype.

In [54]:
# Write your code here
y = np.array([1.9,2.5,3.1]).astype(int)
print(y.dtype)


int64


## 6. Vectorized Arithmetic & Boolean Masking

_`a + b`, `a * b`, `a ** 2` → element-wise ops | `arr[arr > x]` → boolean filtering_


**Q6.1** Create two same-size arrays and compute their sum, product, and squares.

In [57]:
# Write your code here
t = np.arange(4)
u = np.arange(5,9)
print(t+u)
print(t*u)
print(t**u)

[ 5  7  9 11]
[ 0  6 14 24]
[   0    1  128 6561]


**Q6.2** Create an array of 10 random-looking numbers of your choice, then filter out only values greater than 15 using a boolean mask.

In [58]:
# Write your code here
p = np.arange(8,40,4)
print(p[p>15])


[16 20 24 28 32 36]


## 7. Random Module

_`np.random.seed(n)` → reproducibility | `.rand()` → uniform | `.randn()` → normal | `.randint(low,high,size)` → random ints | `.choice(arr,size)` → random sample | `.shuffle(arr)` → shuffle in place_


**Q7.1** Set a seed, generate a 3x3 uniform random array, and confirm reproducibility by rerunning with the same seed.

In [62]:
# Write your code here


np.random.seed(23)

arr1 = np.random.rand(3, 3)

print("First run:")
print(arr1)


np.random.seed(23)
arr2 = np.random.rand(3, 3)


print(arr2)


print("\nReproducible:", np.array_equal(arr1, arr2))

First run:
[[0.51729788 0.9469626  0.76545976]
 [0.28239584 0.22104536 0.68622209]
 [0.1671392  0.39244247 0.61805235]]
[[0.51729788 0.9469626  0.76545976]
 [0.28239584 0.22104536 0.68622209]
 [0.1671392  0.39244247 0.61805235]]

Reproducible: True


**Q7.2** Generate 5 values from a normal distribution and 5 random integers between 1-100.

In [ ]:
# Write your code here



normal = np.random.normal(size=5)
random = np.random.randint(1, 101, size=5)

print("Normal distribution:", normal)
print("Random integers:", random)


Normal distribution: [ 0.74456081 -1.65889741 -0.16834479 -0.35671283  0.85026465]
Random integers: [16 87 84 59 26]


**Q7.3** Randomly pick 3 values (no repeats) from a list of 8 items, then shuffle a 1-10 array.

In [ ]:
# Write your code here



## 8. Reduction & Axis Rules

_`.sum()` / `.mean()` / `np.median()` → aggregations | `axis=0` → column-wise | `axis=1` → row-wise_


**Q8.1** Create a 3x3 matrix. Find the total sum, sum along axis=0, sum along axis=1.

In [66]:
# Write your code here
r = np.arange(9).reshape(3,3)
print(r)
print(r.sum(axis=0))
print(r.sum(axis=1))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]
[ 3 12 21]


**Q8.2** Find the mean and median of the same matrix.

In [ ]:
# Write your code here
print(np.median(r))
print(r.mean())



4.0
4.0


## 9. Broadcasting

_Shapes match if equal or one of them is 1 (compared right to left) | smaller array auto-expands to fit_


**Q9.1** Add a (3,3) ones matrix with a 1D array of length 3 — observe the broadcast.

In [69]:
# Write your code here
i = np.array([1,2,3])
print(i+r)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


**Q9.2** Create a row vector (1,3) and column vector (3,1), add them, and check the resulting shape.

In [72]:
# Write your code here
row = np.arange(0,3).reshape(1,3)
print(row)
col = np.arange(0,3).reshape(3,1)
print(col)

print(row+col)
print((row+col).shape)


[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
(3, 3)


## 10. Reshaping & Dimension Expansion

_`reshape(-1, n)` → auto-calculate the other dimension | `arr[np.newaxis, :]` → row vector | `arr[:, np.newaxis]` → column vector_


**Q10.1** Create a 12-element array and reshape it using -1 so it has 4 columns.

In [ ]:
# Write your code here
np.arange(12).reshape(-1,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Q10.2** Take a 3-element 1D array and convert it into a row vector and a column vector using np.newaxis.

In [79]:
# Write your code here
er = np.array([1,2,3])
print(er[np.newaxis,:])
print(er[:,np.newaxis])


[[1 2 3]]
[[1]
 [2]
 [3]]


## 11. Flatten vs Ravel

_`.flatten()` → returns a copy (original safe) | `.ravel()` → returns a view (original can change too)_


**Q11.1** Create a 2D array, flatten it with both methods, modify the first element of each result, and check which one affects the original array.

In [91]:
# Write your code here
er1 = np.arange(12).reshape(6,2)
print(er1.flatten())
print(er1.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


## 12. Stacking & Concatenation

_`np.vstack()` → stack rows | `np.hstack()` → stack columns | `np.concatenate(axis=)` → general version_


**Q12.1** Create two 2x2 arrays. Combine them using vstack, hstack, and concatenate on both axis=0 and axis=1.

In [92]:
# Write your code here
t1 = np.arange(4).reshape(2,2)
t2 = np.arange(4,8).reshape(2,2)
print(np.vstack((t1,t2)))
print(np.hstack((t1,t2)))
print(np.concatenate((t1,t2),axis=0))
print(np.concatenate((t1,t2),axis=1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]


## 13. np.where — Conditional Logic

_`np.where(cond, a, b)` → element-wise if/else | `np.where(cond)` → returns matching indices_


**Q13.1** Create a 6-element array. Label each value 'High' or 'Low' based on a threshold using np.where.

In [93]:
# Write your code here
op = np.array([1,2,3,4,5,6])
thresold = 3

lab = np.where(op>thresold,"high","low")
print(lab)

['low' 'low' 'low' 'high' 'high' 'high']


**Q13.2** Use np.where (without true/false args) to find the indices of values above that threshold.

In [94]:
# Write your code her

lab2 = np.where(op>thresold)
print(lab2)


(array([3, 4, 5]),)


## 14. Matrix Operations & Transpose

_`*` → element-wise multiply | `@` / `np.dot()` → matrix multiplication | `.T` → transpose (rows ↔ cols)_


**Q14.1** Create two 2x2 matrices. Compute their element-wise product and their matrix product (using both @ and np.dot).

In [96]:
# Write your code here
k = np.arange(4).reshape(2,2)
l = np.arange(4,8).reshape(2,2)
print(k@l)
print(np.dot(k,l))

[[ 6  7]
 [26 31]]
[[ 6  7]
 [26 31]]


**Q14.2** Print the transpose of the first matrix.

In [97]:
# Write your code here
print(k.T)

[[0 2]
 [1 3]]


---
## CRUD Operations on Arrays

_Create, Read, Update, Delete/Insert — arrays are fixed-size, so delete/insert return a new array rather than modifying in place._


## 15. CRUD — Create & Read

_Create = `np.array()`/creation helpers | Read = indexing & slicing_


**Q15.1** Create a 1D array of 8 integers and a 2D array of shape (3,3).

In [101]:
# Write your code here


n = np.array([1,2,3,4,5,6,7,8])
print(n)
m = np.arange(9).reshape(3,3)
print(m)

[1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Q15.2** Read the element at index 3 from the 1D array, and the middle row from the 2D array.

In [103]:
# Write your code here
print(n[3])
print(m[1,2])


4
5


## 16. CRUD — Update

_`arr[i] = val` or `arr[slice] = val` → updates values directly (arrays are mutable)_


**Q16.1** Update index 2 of your 1D array to 100.

In [104]:
# Write your code here
n[2] = 100


**Q16.2** Update the entire second row of your 2D array to [0, 0, 0].

In [105]:
# Write your code here
m[1,1]=0


## 17. CRUD — Delete & Insert

_`np.delete(arr, idx, axis=)` → remove & return new array | `np.insert(arr, idx, val)` → insert value | `np.append(arr, val)` → add at the end_


**Q17.1** Delete the element at index 0 from your 1D array (store as a new variable).

In [ ]:
# Write your code here
np.delete(n,0)

**Q17.2** Delete the last column from your 2D array.

In [106]:
# Write your code here
np.delete(m,1,axis=0    )

array([[0, 1, 2],
       [6, 7, 8]])

**Q17.3** Use np.append to add 99 to the end of your 1D array, and np.insert to insert 50 at index 1.

In [107]:
# Write your code here

np.append(n,99)


array([  1,   2, 100,   4,   5,   6,   7,   8,  99])

## 18. Combined Practice

_No new functions — just combining what's covered above_


**Q18.1** Create a 5x5 array (1-25), extract its center 3x3 block, then find the row-wise sum of that block.

In [115]:
# Write your code here
real = np.arange(1,26).reshape(5,5)
print(real)
print(real[1:4,1:4])



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


**Q18.2** Create two 1D int arrays, stack them with vstack, add 0.5 to the result and check the dtype coercion.

In [117]:
# Write your code here

q = np.array([1,2,3,4])
r = np.array([5,6,7,8])

x =np.vstack((q,r))
print(x)
y = x+0.5
print(y.dtype)


[[1 2 3 4]
 [5 6 7 8]]
float64


**Q18.3** Create a 4x4 matrix with np.diag() using diagonal values 2,4,6,8, then find its transpose.

In [120]:
# Write your code here
ok=np.diag((2,4,6,8))
print(ok)
print(ok.T)




[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
