In [1]:
import numpy as np


In [6]:
arr = np.arange(24).reshape(3,4,2)
arr1= np.arange(24).reshape(3,4,2)


print(arr+arr1)


[[[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]

 [[16 18]
  [20 22]
  [24 26]
  [28 30]]

 [[32 34]
  [36 38]
  [40 42]
  [44 46]]]


In [13]:



ar = np.array([3,4,5,7]).reshape(1,-1) # use -1 for auto dimensions
print("row vector:",ar)

ar3= np.array([3,4,5,6]).reshape(-1,1)
print("column vector:",ar3)
print(ar+ar3)


row vector: [[3 4 5 7]]
column vector: [[3]
 [4]
 [5]
 [6]]
[[ 6  7  8 10]
 [ 7  8  9 11]
 [ 8  9 10 12]
 [ 9 10 11 13]]


In [ ]:
#question 

a = np.ones((3,4))

print(a)
b = np.array([10,20,30]).reshape(3,1)
print(a+b)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]


In [24]:
#question 2
x = np.arange(6).reshape(2,3)
y = np.arange(6).reshape(2,3)
print(x+y)

[[ 0  2  4]
 [ 6  8 10]]


In [ ]:
#ques 3


In [ ]:
# ques 4


In [25]:
# stacking arrays

r = np.array([[1,2,3],[4,5,6]])
s = np.array([[7,8,9],[10,11,12]])
arr4 = np.arange(12).reshape(2,6)
print("row wise stacking:",np.vstack((r,s)))
print("column wise stacking:",np.hstack((r,s)))


row wise stacking: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
column wise stacking: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# concatenation of arrays
# np.concatenate(arrays, axis=0)
# axis=0 for row wise concatenation
# axis=1 for column wise concatenation
# jis order me array pass krenge usi order me stacking hogi 

print("row wise concatenation:", np.concatenate((r,s), axis=0)) # row wise concatenation
print("column wise concatenation:", np.concatenate((r,s), axis=1)) # column wise concatenation



row wise concatenation: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
column wise concatenation: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [31]:
# np.where

arr = np.array([2,-10,20,-15,-18,10])
arr1 = np.where(arr<0,0,arr)
print(arr1)
print(arr)

arr2 = np.array([20,40,55,75,80,85])
arr3 = np.where(arr2<=40,"fail","1")
print(arr3)

[ 2  0 20  0  0 10]
[  2 -10  20 -15 -18  10]
['fail' 'fail' '1' '1' '1' '1']
